-- Server-generated verification code.
--
-- Initial implementation (migration 013) was based on Gateway-generated
-- codes verified via checkVerificationStatus. After discovering that
-- gateway.telegram.org/api/* always returns "Bad request" and the
-- correct base URL is gatewayapi.telegram.org/ — we switched to the
-- simpler "server generates code, passes to Gateway" pattern.
--
-- Now we store the actual 6-digit code we asked Gateway to deliver,
-- and verify by direct string compare on the user's submission.
-- Removes one HTTPS round-trip per login.
--
-- HISTORICAL NOTE: this migration originally did
--   ALTER TABLE verification_attempts ADD COLUMN code TEXT;
-- but migration 013 was edited in-place AFTER prod had already applied
-- the original version. The new 013 now includes `code TEXT NOT NULL`
-- directly in the CREATE TABLE — so on a fresh deploy this 014 would
-- error with "duplicate column name: code".
--
-- Prod is unaffected (014 already ran against the original 013 schema
-- and is recorded in schema_migrations as completed). For fresh DB
-- installs we make this migration an explicit no-op.

SELECT 1 WHERE 0;  -- no-op
